### ISSUE TITLE
api.js didn't return a function

### ISSUE THREAD

**Issue by liubko** [jupl/traceur-loader#10]
I have problems with building project on Windows or Linux.

Basically what I have is:

```
 webpack 1.4.14
 traceur-loader 0.6.3
 main.js // with 'Hello world'
```

When I run

```
webpack src/main.js
```

I get an error:

```
ERROR in Loader ../traceur-issue/node_modules/traceur-loader/node_modules/traceur/src/node/api.js?runtime=true&sourceMaps=true didn't return a function
@ ./~/traceur-loader/~/traceur/bin/traceur-runtime.js 1:0-129
```

To illustrate my problem I made a [repo with with my example](https://github.com/liubko/traceur-issue)

Run:

```
git clone git@github.com:liubko/traceur-issue.git
cd traceur-issue
npm install
npm run build
```

**Comment by liubko** [comment]
in _webpack.config_ I change 

```
{ test: /\.js$/, loader: "traceur?runtime=true&sourceMaps=true"}
```

to

```
{ test: /\.js$/, loader: "traceur-loader?runtime=true&sourceMaps=true"}
```

I got a build without an error, but when I open _index.html_, I see an error in browser's console

```
Uncaught ReferenceError: Reflect is not defined
```

I got this error only on _Windows_, on _Linux_ it works fine

**Comment by zbow** [comment]
困了  也不知道写啥  这样能行不？
