### ISSUE TITLE
Reflect is not defined 

### ISSUE THREAD

**Issue by mosch** [jupl/traceur-loader#2]
Using the traceur-loader within webpack an `Uncaught ReferenceError: Reflect is not defined` raises when the bundled javascript get's executed. The modules get's called with via `module.exports = {}.call(Reflect.global);` but the Reflect.global is not defined. 

Am I doing this wrong?

**Comment by jupl** [comment]
Do you have a code snippet that I can compile to reproduce?

**Comment by jeroencranendonk-wf** [comment]
I'm experiencing the same issue. Here's a minimal case that illustrates the issue: https://gist.github.com/81af3482935eef3eb7d5

With traceur-loader, the error 'Uncaught ReferenceError: Reflect is not defined' is logged to the console. Without traceur-loader, the example works as expected.

**Comment by jeroencranendonk-wf** [comment]
Note that compiling main.js with Traceur first, then running webpack with the compiled file (without traceur-loader) also works correctly.

**Comment by jupl** [comment]
~~Use this for your Webpack config:~~ EDIT: I was looking at the wrong config.

**Comment by jupl** [comment]
Check the updated README and see the updated test regex. That fixes it for me.

**Comment by jeroencranendonk-wf** [comment]
The updated regex works. Thanks for looking into it.
