### ISSUE TITLE
Ability to disable sourceMaps

### ISSUE THREAD

**Issue by Kagami** [jupl/traceur-loader#8]
Hi. Could you please explain why do you force `sourceMaps` option to [always be true](https://github.com/jupl/traceur-loader/blob/master/index.js#L22)? Is there some good reason to always enable the source maps?
Do you mind to move it to `defaults` options instead?

**Comment by jupl** [comment]
It was set to `true` because source maps are handed off to Webpack and you tell/configure Webpack builds to include/exclude source maps like in https://github.com/webpack/coffee-loader.

**Comment by jupl** [comment]
The only reason I can think of moving it to defaults so a user can toggle it would be for performance, although I haven't noticed it or heard issues about it. Otherwise I can just add it to defaults.

**Comment by Kagami** [comment]
Yes, the first reason is performance. The other is that with the default settings I get this source map declaration: `//# sourceMappingURL=<compileOutput>` and browser does HTTP request which fails with 404. The third is that someone may want to use different value for this option (e.g. [inline](https://github.com/google/traceur-compiler/blob/master/src/Compiler.js#L266)).

**Comment by jupl** [comment]
Good enough for me.

**Comment by jupl** [comment]
Need to add some code now to accommodate lack of source maps.

**Comment by Kagami** [comment]
Thanks!

**Comment by nesheroj** [comment]
I'm also getting the '%3CcompileOutput%3E 404 (Not Found)' error when the browser tries to fetch the sourcemaps, but I see no issue reported, is there something I'm missing? Is this supposed to happen?

**Comment by Kagami** [comment]
@nesukun now you can specify `sourceMaps=false` option.
